### ISSUE TITLE
Superimposed user profile avatar

### ISSUE THREAD

**Issue by esenjin** [NYRI4/Couve#30]
Hello, my profile avatar is shifted to the left and is superimposed on the server list column.

![Sans titre](https://github.com/NYRI4/Couve/assets/41757656/42bb4862-acfb-4ced-b828-80546ef7537f)

**Comment by NYRI4** [comment]
Yes, that's how it's supposed to be 🤔

**Comment by esenjin** [comment]
Wouldn't it be better to put it back where it belongs, a little more to the right with the nickname, or to continue the background color to the left? Two graphic elements superimposed like this give the impression of a display problem, especially as the mouse wheel doesn't allow you to navigate the list of servers when the pointer is at this level.

**Comment by NYRI4** [comment]
I find it great on that spot, I'm not the creator of the theme by the way, just a maintainer and this was part of the theme since the beginning, as it was inspired from this design : 

![discord_redesign_-_dribbble_4x](https://github.com/NYRI4/Couve/assets/65369563/05a9abc1-c3e9-4c37-8cce-1e7cd96ce7ad)
